{{ if not .Values.config.queryAdminPasswordExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamspeak-server.fullname" . }}
  labels:
    {{- include "teamspeak-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "{{ .Values.config.queryAdminPassword }}"
{{- end }}